name: 'Duplicate code detection tool'
description: 'Detect similarities between source code files'
inputs:
  github_token:
    description: 'The GitHub token'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check'  
  color: 'green'
