name: 'Pull request comments from clang-tidy reports'
description: 'Post clang-tidy warnings as review comments on pull requests'
inputs:
  github-token:
    description: 'The GitHub token'
    required: true
  clang-tidy-fixes:
    description: 'Path to the clang-tidy fixes YAML file'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check'  
  color: 'green'
